services:
  js-app:
    image: nguyenducmanh247/js-app:2.0
    ports:
      - 3000:3000
  mongodb:
    image: mongo:8.0-noble
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=manh
      - MONGO_INITDB_ROOT_PASSWORD=manh
    volumes:
      - mongo-data:/data/db
  mongo-express:
    image: mongo-express:1.0.2-20-alpine3.19
    ports:
      - 8081:8081
    restart: always
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=manh
      - ME_CONFIG_MONGODB_ADMINPASSWORD=manh
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_URL=mongodb://manh:manh@mongodb:27017/
    depends_on:
      - "mongodb"
volumes:
  mongo-data:
    driver: local
