apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-configmap
  namespace: jsa
data:
  # use for js-app
  full-url: mongodb://manh:manh@mongodb-service:27017/

  # use for mongo-express
  host-only: mongodb-service
